### ISSUE TITLE
Adding VPC settings to config

### ISSUE THREAD

**Issue by eddeee888** [serverless-components/express#22]
Hello! 

I'm trying to use this component in a VPC and since there is no settings for VPC, I have to go to my deployed Lambda and manually add it in. This is fine in the short term but it would be nice to have it built-in as a feature for this component.

Here's what I had to do manually:

- Deploy the lambda once
- Attach `AWSLambdaVPCAccessExecutionRole` to the role that is used by the lambda
- Edit VPC settings, add VPC, subnet and security groups in the lambda dashboard

Maybe there could be a new input called `vpc` and looks similar to normal serverless template?

```yml
inputs:
  vpc:
      securityGroupIds:
        - securityGroupId1
        - securityGroupId2
      subnetIds:
        - subnetId1
        - subnetId2
```

Is this something that could potentially be added in this component? Maybe there's an easier way? Happy to discuss this further. :)
