### ISSUE TITLE
Is it possible to use EDGE domains?

### ISSUE THREAD

**Issue by mightyinsomniak** [serverless-components/express#30]
If not, how can i force the usage of  "API Gateway V1"?
I currently get an error when i try to deploy a simple express app with my custom domain

```
component: express     
name: myname            
org: myorg              
app: myapp                   

inputs:
  src: ./src
  domain: my-cool-domain.com
```

"Only REGIONAL domain names can be managed through the API Gateway V2 API. For EDGE domain names, please use the API Gateway V1 API. Also note that only REST APIs can be attached to EDGE domain names"

aws does not give me the opprtunity to use regions in r53, i only have acces to the "global" region

not sure how to proceed.
