### ISSUE TITLE
Can't set base path mapping for domain stage

### ISSUE THREAD

**Issue by kueckermann** [serverless-components/express#33]
It doesnt seem to be possible to define a base path for a domain in serverless.yml.
This would be great since currently, I need to do it manually.

**Comment by eahefnawy** [comment]
Not sure what you mean @kueckermann 🤔 ... could you clarify? How would that domain look like in `serverless.yml`?

**Comment by kueckermann** [comment]
@eahefnawy before using the serverless express component we were using the standard serverless framework with functions. On that we used to use the serverless-domain-manager plugin, which allowed for defining a base path for API gateway. This was valuable because we could with the same domain and point the base path "api.example.com/**dev**" to our dev stage API, "api.example.com/**staging**" to our staging API, etc.

I could imagine it would look something like this in serverless.yml, dynamically setting the base path to the stage:
```yml
inputs:
  src: ./                        
  description: My Express App    
  domain: api.serverless.com   
  basePath: ${opt:stage}
```

**Comment by eahefnawy** [comment]
@kueckermann wouldn't it be the same if you change the subdomain according to the stage?

```yml
stage: dev # you can change this to set the stage

inputs:
  domain: ${stage}.api.serverless.com
```

So you'd get `https://dev.api.serverless.com` in dev, and `https://staging.api.serverless.com` in staging.

You could also set the entire domain as an env variable, and have its value stored differently for each stage `.env` file. So the yml file would be:

```yml

inputs:
  domain: ${env:DOMAIN}
```

```
# .env.dev

DOMAIN=dev.api.serverless.com
```

```
# .env.prod

DOMAIN=api.serverless.com
```

Does that help?
