### ISSUE TITLE
Images not served properly

### ISSUE THREAD

**Issue by Pato94** [serverless-components/express#55]
I'm experiencing the same issue described [here](https://github.com/vendia/serverless-express/issues/104). I'd like to test this solution, but right now I'm using this component, and as far as I know it does not provide any configuration to specify these `content-types`.

I looked into [this file](https://github.com/serverless-components/express/blob/master/src/_express/handler.js#L59) and I noticed the server is not being created with any parameter.

My workaround is going to be not using this component and creating the server myself, but I'd like to use this component in the future. Is it possible to add this `content-types` as a configuration parameter?

**Comment by gjgd** [comment]
I'm also experiencing the same issue with serving images through the express component

**Comment by nemani** [comment]
Hey any updates on this ?! I have been pulling out my hair trying to understand why i cant display images.

**Comment by nemani** [comment]
Fixed it! 
you need to set the env variable for the `binary_content_types` to change the return for [`isBinary()`](https://github.com/dougmoscrop/serverless-http/blob/63c6d3957a6fbfd72c0258d4c39457dc685bac45/lib/provider/aws/is-binary.js)

```yaml
component: express
name: express-starter

inputs:
  src:
    src: ./
    hook: npm run build
    dist: build
  timeout: 30
  memory: 1024
  env:
    FONTCONFIG_PATH: '/var/task/fonts'
    BINARY_CONTENT_TYPES: 'image/png, image/jpg'
```
