### ISSUE TITLE
Some dynamic template variables don't work

### ISSUE THREAD

**Issue by pss4281** [serverless-components/express#69]
Hi there,
I'm trying to read a config file and read its contents into an ENV variable, however what I'm getting is an original config string partially interpreted. The 'stage' variable gets replaced properly but everything else is not.

Here's my template:

```yml
component: express
name: api

inputs:
  roleName: ${output:api-distributions-permissions.name}
  src: ./src
  # domain: api.${env:domain}
  # Environment variables
  env:
    STAGE: ${stage}
    SCHEMA_NAME: ${file(../../environments.yml):environments.${stage}.dbSchemaName}
```

Resulting function (you may notice how 'stage' was properly replaced with the correct value):

<img width="832" alt="Screenshot 2021-03-17 at 18 58 50" src="https://user-images.githubusercontent.com/91559/111549592-d2e19800-8752-11eb-95ea-9e172e1a3ecf.png">

This exact ENV var definition works in a non-component based service, properly reading the file and putting its content as a ENV variable value. It appears that not all of the dynamic variables available for regular services can be used for component-based services. What are the best practices to solve this?

```
Framework Core: 2.30.3
Plugin: 4.5.1
SDK: 4.2.0
Components: 3.7.4
```

Thanks in advance!
